// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgguroafjxxsoebvzhzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZ3Vyb2Fmanh4c29lYnZ6aHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTk1NjcsImV4cCI6MjA2NjQzNTU2N30.7xfWub3Gk1Kh-5xwrV1k4K8RWeLudxpS3-L2KYUOUnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);